name: CD

on:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo
        run: |
          echo "Code merged to main"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
